version: "3.7"

services:
  db:
    image: postgres:14.10-alpine
    restart: always

    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
  
  backend:  
    build: 
      context: ./Back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: 
      context: /Front/front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend